In [1]:
import pandas as pd

In [2]:
flights= {'Quotes': [{'QuoteId': 1,
   'MinPrice': 92.0,
   'Direct': False,
   'OutboundLeg': {'CarrierIds': [1065],
    'OriginId': 81727,
    'DestinationId': 50290,
    'DepartureDate': '2020-12-12T00:00:00'},
   'QuoteDateTime': '2020-09-21T10:49:00'},
  {'QuoteId': 2,
   'MinPrice': 133.0,
   'Direct': True,
   'OutboundLeg': {'CarrierIds': [851],
    'OriginId': 81727,
    'DestinationId': 50290,
    'DepartureDate': '2020-12-12T00:00:00'},
   'QuoteDateTime': '2020-09-21T10:49:00'}],
 'Places': [{'PlaceId': 50290,
   'IataCode': 'EWR',
   'Name': 'New York Newark',
   'Type': 'Station',
   'SkyscannerCode': 'EWR',
   'CityName': 'New York',
   'CityId': 'NYCA',
   'CountryName': 'United States'},
  {'PlaceId': 60987,
   'IataCode': 'JFK',
   'Name': 'New York John F. Kennedy',
   'Type': 'Station',
   'SkyscannerCode': 'JFK',
   'CityName': 'New York',
   'CityId': 'NYCA',
   'CountryName': 'United States'},
  {'PlaceId': 65633,
   'IataCode': 'LGA',
   'Name': 'New York LaGuardia',
   'Type': 'Station',
   'SkyscannerCode': 'LGA',
   'CityName': 'New York',
   'CityId': 'NYCA',
   'CountryName': 'United States'},
  {'PlaceId': 81727,
   'IataCode': 'SFO',
   'Name': 'San Francisco International',
   'Type': 'Station',
   'SkyscannerCode': 'SFO',
   'CityName': 'San Francisco',
   'CityId': 'SFOA',
   'CountryName': 'United States'}],
 'Carriers': [{'CarrierId': 819, 'Name': 'Aegean Airlines'},
  {'CarrierId': 851, 'Name': 'Alaska Airlines'},
  {'CarrierId': 870, 'Name': 'jetBlue'},
  {'CarrierId': 1065, 'Name': 'Frontier Airlines'},
  {'CarrierId': 1721, 'Name': 'Sun Country Airlines'},
  {'CarrierId': 1793, 'Name': 'United'},
  {'CarrierId': 1902, 'Name': 'Southwest Airlines'}],
 'Currencies': [{'Code': 'USD',
   'Symbol': '$',
   'ThousandsSeparator': ',',
   'DecimalSeparator': '.',
   'SymbolOnLeft': True,
   'SpaceBetweenAmountAndSymbol': False,
   'RoundingCoefficient': 0,
   'DecimalDigits': 2}]}

In [3]:
from datetime import datetime

def find_flights_same_price(start_date, end_date):
    
    Places = pd.json_normalize(flights['Places'])
    Carriers = pd.json_normalize(flights['Carriers'])
    Quotes = pd.json_normalize(flights['Quotes'])
    Quotes['OutboundLeg.CarrierIds'] = Quotes['OutboundLeg.CarrierIds'].apply(lambda x: int(x[0]))
    
    quotes_and_places_dest=pd.merge(Quotes, Places, left_on='OutboundLeg.DestinationId', right_on ='PlaceId')
    quotes_and_places_dest = quotes_and_places_dest.rename(columns={"Name": "Destination_Name", "SkyscannerCode": "Destination_Code", "CityName":"Destination_City_Name", "CityId":"Destination_City_id",
                                                                              "CountryName":"Destination_Country_Name","OutboundLeg.DepartureDate":"DepartureDate","OutboundLeg.CarrierIds": "CarrierIds",
                                                                              "OutboundLeg.OriginId":"OriginId","OutboundLeg.DestinationId":"DestinationId"})
    quotes_and_places = pd.merge(quotes_and_places_dest, Places, left_on='OriginId', right_on ='PlaceId')
    quotes_and_places=quotes_and_places.drop(columns=['PlaceId_y','Type_x','IataCode_x','IataCode_y','Type_y'])
    quotes_and_places= quotes_and_places.rename(columns={"Name": "Origin_Name", "SkyscannerCode": "Origin_Code", "CityName":"Origin_City_Name", "CityId":"Origin_City_id",
                                                                                  "CountryName":"Origin_Country_Name"})
    quotes_and_places_and_carriers=pd.merge(quotes_and_places, Carriers, left_on='CarrierIds', right_on ='CarrierId')
    quotes_and_places_and_carriers=quotes_and_places_and_carriers.rename(columns={"Name": "Airline"}) 
    quotes_and_places_and_carriers=quotes_and_places_and_carriers.drop(columns=['PlaceId_x','CarrierIds'])
    quotes_and_places_and_carriers['DepartureDate'] = pd.to_datetime(quotes_and_places_and_carriers['DepartureDate'])
    
    quotes_and_places_and_carriers.set_index(quotes_and_places_and_carriers['DepartureDate'], drop=False, append=False, inplace=True)
    
    
    return pd.DataFrame({'Price USD':quotes_and_places_and_carriers['MinPrice'],
                        'Origin':quotes_and_places_and_carriers['Origin_Name'],
                        'Origin_Code':quotes_and_places_and_carriers['Origin_Code'],
                        'Origin_City_Name':quotes_and_places_and_carriers['Origin_City_Name'],
                        'Arrival':quotes_and_places_and_carriers['Destination_Name'],
                        'Arrival_Code':quotes_and_places_and_carriers['Destination_Code'],
                        'Arrival_City_Name':quotes_and_places_and_carriers['Destination_City_Name'],
                        'Company':quotes_and_places_and_carriers['Airline']})

In [4]:
find_flights_same_price( '2020-12-10', '2020-12-15')

,Price USD,Origin,Origin_Code,Origin_City_Name,Arrival,Arrival_Code,Arrival_City_Name,Company
DepartureDate,,,,,,,,
2020-12-12,92.0,San Francisco International,SFO,San Francisco,New York Newark,EWR,New York,Frontier Airlines
2020-12-12,133.0,San Francisco International,SFO,San Francisco,New York Newark,EWR,New York,Alaska Airlines