
# Lab | Working with APIs

#### Instructions 

Following the class example, create a function that returns the price, names of origin and arrival airports and the name of the company. Do it for all the flights between two dates that cost the same.

In [66]:
flight_data = {
    'Quotes': [
        {
            'QuoteId': 1,
            'MinPrice': 92.0,
            'Direct': False,
            'OutboundLeg': {
                'CarrierIds': [1065],
                'OriginId': 81727,
                'DestinationId': 50290,
                'DepartureDate': '2020-12-12T00:00:00'
            },
            'QuoteDateTime': '2020-09-21T10:49:00'
        },
        {
            'QuoteId': 2,
            'MinPrice': 133.0,
            'Direct': True,
            'OutboundLeg': {
                'CarrierIds': [851],
                'OriginId': 81727,
                'DestinationId': 50290,
                'DepartureDate': '2020-12-12T00:00:00'
            },
            'QuoteDateTime': '2020-09-21T10:49:00'
        },
        {
            'QuoteId': 3,
            'MinPrice': 150.0,
            'Direct': True,
            'OutboundLeg': {
                'CarrierIds': [1902],
                'OriginId': 81727,
                'DestinationId': 60987,
                'DepartureDate': '2020-12-13T00:00:00'
            },
            'QuoteDateTime': '2020-09-22T10:49:00'
        }
    ],
    'Places': [
        {
            'PlaceId': 50290,
            'IataCode': 'EWR',
            'Name': 'New York Newark',
            'Type': 'Station',
            'SkyscannerCode': 'EWR',
            'CityName': 'New York',
            'CityId': 'NYCA',
            'CountryName': 'United States'
        },
        {
            'PlaceId': 60987,
            'IataCode': 'JFK',
            'Name': 'New York John F. Kennedy',
            'Type': 'Station',
            'SkyscannerCode': 'JFK',
            'CityName': 'New York',
            'CityId': 'NYCA',
            'CountryName': 'United States'
        },
        {
            'PlaceId': 65633,
            'IataCode': 'LGA',
            'Name': 'New York LaGuardia',
            'Type': 'Station',
            'SkyscannerCode': 'LGA',
            'CityName': 'New York',
            'CityId': 'NYCA',
            'CountryName': 'United States'
        },
        {
            'PlaceId': 81727,
            'IataCode': 'SFO',
            'Name': 'San Francisco International',
            'Type': 'Station',
            'SkyscannerCode': 'SFO',
            'CityName': 'San Francisco',
            'CityId': 'SFOA',
            'CountryName': 'United States'
        }
    ],
    'Carriers': [
        {
            'CarrierId': 819,
            'Name': 'Aegean Airlines'
        },
        {
            'CarrierId': 851,
            'Name': 'Alaska Airlines'
        },
        {
            'CarrierId': 870,
            'Name': 'jetBlue'
        },
        {
            'CarrierId': 1065,
            'Name': 'Frontier Airlines'
        },
        {
            'CarrierId': 1721,
            'Name': 'Sun Country Airlines'
        },
        {
            'CarrierId': 1793,
            'Name': 'United'
        },
        {
            'CarrierId': 1902,
            'Name': 'Southwest Airlines'
        }
    ],
    'Currencies': [
        {
            'Code': 'USD',
            'Symbol': '$',
            'ThousandsSeparator': ',',
            'DecimalSeparator': '.',
            'SymbolOnLeft': True,
            'SpaceBetweenAmountAndSymbol': False,
            'RoundingCoefficient': 0,
            'DecimalDigits': 2
        }
    ]
}

In [99]:
# Make a dummie 4th flight

new_flight = {
    'QuoteId': 4,  # New QuoteId
    'MinPrice': 92.0,  # Same cost as QuoteId 1
    'Direct': False,  # Copying the Direct status
    'OutboundLeg': {
        'CarrierIds': [1065],  # Assuming the same carrier for simplicity
        'OriginId': 81727,  # Same origin as QuoteId 1
        'DestinationId': 50290,  # Same destination as QuoteId 1
        'DepartureDate': '2020-12-14T00:00:00'  # New departure date
    },
    'QuoteDateTime': '2020-09-23T10:49:00'  # New quote date and time
}

# Adding the new flight to the Quotes list
flight_data['Quotes'].append(new_flight)

[(1, '2020-12-12T00:00:00'),
 (2, '2020-12-12T00:00:00'),
 (3, '2020-12-13T00:00:00'),
 (4, '2020-12-14T00:00:00')]

In [100]:
flight_data.keys() # ['Quotes', 'Places', 'Carriers', 'Currencies']

dict_keys(['Quotes', 'Places', 'Carriers', 'Currencies'])

In [156]:
flight_data['Quotes']

[{'QuoteId': 1,
  'MinPrice': 92.0,
  'Direct': False,
  'OutboundLeg': {'CarrierIds': [1065],
   'OriginId': 81727,
   'DestinationId': 50290,
   'DepartureDate': '2020-12-12T00:00:00'},
  'QuoteDateTime': '2020-09-21T10:49:00'},
 {'QuoteId': 2,
  'MinPrice': 133.0,
  'Direct': True,
  'OutboundLeg': {'CarrierIds': [851],
   'OriginId': 81727,
   'DestinationId': 50290,
   'DepartureDate': '2020-12-12T00:00:00'},
  'QuoteDateTime': '2020-09-21T10:49:00'},
 {'QuoteId': 3,
  'MinPrice': 150.0,
  'Direct': True,
  'OutboundLeg': {'CarrierIds': [1902],
   'OriginId': 81727,
   'DestinationId': 60987,
   'DepartureDate': '2020-12-13T00:00:00'},
  'QuoteDateTime': '2020-09-22T10:49:00'},
 {'QuoteId': 4,
  'MinPrice': 92.0,
  'Direct': False,
  'OutboundLeg': {'CarrierIds': [1065],
   'OriginId': 81727,
   'DestinationId': 50290,
   'DepartureDate': '2020-12-14T00:00:00'},
  'QuoteDateTime': '2020-09-23T10:49:00'}]

In [82]:
flight_data['Places'][0]

{'PlaceId': 50290,
 'IataCode': 'EWR',
 'Name': 'New York Newark',
 'Type': 'Station',
 'SkyscannerCode': 'EWR',
 'CityName': 'New York',
 'CityId': 'NYCA',
 'CountryName': 'United States'}

In [193]:
flight_data['Quotes'][0]['QuoteId']

1

In [97]:
flight_data['Carriers'][5]

{'CarrierId': 1793, 'Name': 'United'}

In [219]:
def flight_info(flight_data):
    """
    Analyzes flight data to identify flights.
    
    Parameters:
    - flight_data: A dictionary containing information about flight quotes, places, and carriers.
    
    Returns:
    - A pandas DataFrame containing flights infos.
    """
    
    # Initialize an empty list to collect flight information
    all_flight_informations = []
        
    # Create mappings from PlaceId and CarrierId to their respective names for easy lookup
    place_mapping = {place['PlaceId']: place['Name'] for place in flight_data['Places']}
    carrier_mapping = {carrier['CarrierId']: carrier['Name'] for carrier in flight_data['Carriers']}
    
    # Iterate over each flight quote to extract and transform relevant information
    for quote in flight_data['Quotes']:
        # Extracting flight details from the quote
        price = quote['MinPrice']
        origin_id = quote['OutboundLeg']['OriginId']
        carrier_id = quote['OutboundLeg']['CarrierIds'][0]
        destination_id = quote['OutboundLeg']['DestinationId']
        departure_date = quote['OutboundLeg']['DepartureDate']

        # Using mappings to get human-readable names for origin and destination
        origin_name = place_mapping[origin_id]
        destination_name = place_mapping[destination_id]
        carrier_name = carrier_mapping[carrier_id]
        
        # Compiling extracted information into a dictionary
        flight_information = {
            'Flight Id': quote['QuoteId'],
            'Price': price,
            'Origin': origin_name,
            'Destination': destination_name,
            'Carrier': carrier_name,
            'Departure Date': departure_date
        }
        
        # Adding the compiled flight information to the list
        all_flight_informations.append(flight_information)
    
    # Converting the list of flight information into a pandas DataFrame
    df = pd.DataFrame(all_flight_informations)
    
    # Returning the DataFrame
    return df

In [220]:
flight_info(flight_data)

,Flight Id,Price,Origin,Destination,Carrier,Departure Date
0,1,92.0,San Francisco International,New York Newark,Frontier Airlines,2020-12-12T00:00:00
1,2,133.0,San Francisco International,New York Newark,Alaska Airlines,2020-12-12T00:00:00
2,3,150.0,San Francisco International,New York John F. Kennedy,Southwest Airlines,2020-12-13T00:00:00
3,4,92.0,San Francisco International,New York Newark,Frontier Airlines,2020-12-14T00:00:00

In [221]:
def flight_info_same_price(flight_data):
    """
    Analyzes flight data to identify flights with the same price but different departure dates.
    
    Parameters:
    - flight_data: A dictionary containing information about flight quotes, places, and carriers.
    
    Returns:
    - A pandas DataFrame containing flights that have the same price but depart on different dates.
    """
    
    # Initialize an empty list to collect flight information
    all_flight_informations = []
        
    # Create mappings from PlaceId and CarrierId to their respective names for easy lookup
    place_mapping = {place['PlaceId']: place['Name'] for place in flight_data['Places']}
    carrier_mapping = {carrier['CarrierId']: carrier['Name'] for carrier in flight_data['Carriers']}
    
    # Iterate over each flight quote to extract and transform relevant information
    for quote in flight_data['Quotes']:
        # Extracting flight details from the quote
        price = quote['MinPrice']
        origin_id = quote['OutboundLeg']['OriginId']
        carrier_id = quote['OutboundLeg']['CarrierIds'][0]
        destination_id = quote['OutboundLeg']['DestinationId']
        departure_date = quote['OutboundLeg']['DepartureDate']

        # Using mappings to get human-readable names for origin and destination
        origin_name = place_mapping[origin_id]
        destination_name = place_mapping[destination_id]
        carrier_name = carrier_mapping[carrier_id]
        
        # Compiling extracted information into a dictionary
        flight_information = {
            'Flight Id': quote['QuoteId'],
            'Price': price,
            'Origin': origin_name,
            'Destination': destination_name,
            'Carrier': carrier_name,
            'Departure Date': departure_date
        }
        
        # Adding the compiled flight information to the list
        all_flight_informations.append(flight_information)
    
    # Converting the list of flight information into a pandas DataFrame
    df = pd.DataFrame(all_flight_informations)
    
    # Converting 'Departure Date' from string to datetime.date for easier comparison
    df['Departure Date'] = pd.to_datetime(df['Departure Date']).dt.date

    # Filtering the DataFrame for flights with the same price but different departure dates
    result = df.groupby('Price').filter(lambda x: len(x['Departure Date'].unique()) > 1)
    
    # Returning the filtered DataFrame
    return result

In [222]:
flight_info_same_price(flight_data)

,Flight Id,Price,Origin,Destination,Carrier,Departure Date
0,1,92.0,San Francisco International,New York Newark,Frontier Airlines,2020-12-12
3,4,92.0,San Francisco International,New York Newark,Frontier Airlines,2020-12-14