In [1]:
import requests
import pandas as pd
import json
from datetime import datetime, timedelta

In [2]:
import warnings

# Ignore all warnings
warnings.filterwarnings("ignore")

# Your code generating warnings here

# Restore default warning behavior if needed
# warnings.filterwarnings("default")

In [3]:
def flatten_dict(dd, separator='_', prefix=''):
        return {f"{prefix}{separator}{k}" if prefix else k: v
                for kk, vv in dd.items()
                for k, v in (flatten_dict(vv, separator, kk).items() if isinstance(vv, dict) else {kk: vv}.items())}

In [4]:
# Testing the API and loop works

In [5]:
start_date = pd.to_datetime(input())
end_date = pd.to_datetime(input())
inbound = input()
outbound = input()


date_list = pd.date_range(start=start_date,end=end_date)

for i in range(0,len(date_list)):
    current_date = start_date + timedelta(days=i)
    
    url = "https://partners.api.skyscanner.net/apiservices/v3/flights/indicative/search"

    payload = { "query": {
            "market": "UK",
            "locale": "en-GB",
            "currency": "EUR",
            "queryLegs": [
                {
                    "originPlace": { "queryPlace": { "iata": inbound } },
                    "destinationPlace": { "queryPlace": { "iata": outbound } },
                     "fixedDate": {
                "year": current_date.year,
                "month": current_date.month,
                "day": current_date.day
            }
                }
            ]
        } }
    headers = {
        "x-api-key": "prtl6749387986743898559646983194"
    }

    response = requests.post(url, json=payload, headers=headers)

    output = response.json()
    results = output['content']['results']
    quotes = results['quotes']

    flattened_results = [flatten_dict(result) for result in quotes.values()]

    if i == 0:
        quote_df = pd.DataFrame.from_records(flattened_results)
    else:
        temp_df = pd.DataFrame.from_records(flattened_results)
        quote_df = quote_df.append(temp_df, ignore_index=True)

quote_df

2023/5/20
2023/5/30
LIS
LTN

,minPrice_amount,minPrice_unit,minPrice_updateStatus,isDirect,outboundLeg_originPlaceId,outboundLeg_destinationPlaceId,outboundLeg_departureDateTime_year,outboundLeg_departureDateTime_month,outboundLeg_departureDateTime_day,outboundLeg_departureDateTime_hour,...,inboundLeg_originPlaceId,inboundLeg_destinationPlaceId,inboundLeg_departureDateTime_year,inboundLeg_departureDateTime_month,inboundLeg_departureDateTime_day,inboundLeg_departureDateTime_hour,inboundLeg_departureDateTime_minute,inboundLeg_departureDateTime_second,inboundLeg_quoteCreationTimestamp,inboundLeg_marketingCarrierId
0,68,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,True,95565055,95565053,2023,5,20,0,...,,,0,0,0,0,0,0,0,
1,123,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,False,95565055,95565053,2023,5,21,0,...,,,0,0,0,0,0,0,0,
2,144,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,True,95565055,95565053,2023,5,21,0,...,,,0,0,0,0,0,0,0,
3,93,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,True,95565055,95565053,2023,5,22,0,...,,,0,0,0,0,0,0,0,
4,54,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,True,95565055,95565053,2023,5,23,0,...,,,0,0,0,0,0,0,0,
5,40,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,True,95565055,95565053,2023,5,24,0,...,,,0,0,0,0,0,0,0,
6,44,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,True,95565055,95565053,2023,5,25,0,...,,,0,0,0,0,0,0,0,
7,39,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,True,95565055,95565053,2023,5,26,0,...,,,0,0,0,0,0,0,0,
8,40,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,True,95565055,95565053,2023,5,27,0,...,,,0,0,0,0,0,0,0,
9,50,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,True,95565055,95565053,2023,5,28,0,...,,,0,0,0,0,0,0,0,
10,159,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,True,95565055,95565053,2023,5,29,0,...,,,0,0,0,0,0,0,0,
11,134,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,False,95565055,95565053,2023,5,29,0,...,,,0,0,0,0,0,0,0,
12,53,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,True,95565055,95565053,2023,5,30,0,...,,,0,0,0,0,0,0,0,

In [6]:
def skyscanner():
    start_date = pd.to_datetime(input('Start Date: '))
    end_date = pd.to_datetime(input('End Date: '))
    inbound = input('Inbound: ')
    outbound = input('Outbound: ')


    date_list = pd.date_range(start=start_date,end=end_date)

    for i in range(0,len(date_list)):
        current_date = start_date + timedelta(days=i)

        url = "https://partners.api.skyscanner.net/apiservices/v3/flights/indicative/search"

        payload = { "query": {
                "market": "UK",
                "locale": "en-GB",
                "currency": "EUR",
                "queryLegs": [
                    {
                        "originPlace": { "queryPlace": { "iata": inbound } },
                        "destinationPlace": { "queryPlace": { "iata": outbound } },
                         "fixedDate": {
                    "year": current_date.year,
                    "month": current_date.month,
                    "day": current_date.day
                }
                    }
                ]
            } }
        headers = {
            "x-api-key": "prtl6749387986743898559646983194"
        }

        response = requests.post(url, json=payload, headers=headers)

        output = response.json()
        results = output['content']['results']
        quotes = results['quotes']

        flattened_results = [flatten_dict(result) for result in quotes.values()]

        if i == 0:
            quote_df = pd.DataFrame.from_records(flattened_results)
        else:
            temp_df = pd.DataFrame.from_records(flattened_results)
            quote_df = quote_df.append(temp_df, ignore_index=True)

    return quote_df

In [7]:
skyscanner()

Start Date: 2023/5/20
End Date: 2023/5/30
Inbound: LIS
Outbound: MAD

,minPrice_amount,minPrice_unit,minPrice_updateStatus,isDirect,outboundLeg_originPlaceId,outboundLeg_destinationPlaceId,outboundLeg_departureDateTime_year,outboundLeg_departureDateTime_month,outboundLeg_departureDateTime_day,outboundLeg_departureDateTime_hour,...,inboundLeg_originPlaceId,inboundLeg_destinationPlaceId,inboundLeg_departureDateTime_year,inboundLeg_departureDateTime_month,inboundLeg_departureDateTime_day,inboundLeg_departureDateTime_hour,inboundLeg_departureDateTime_minute,inboundLeg_departureDateTime_second,inboundLeg_quoteCreationTimestamp,inboundLeg_marketingCarrierId
0,33,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,True,95565055,95565077,2023,5,20,0,...,,,0,0,0,0,0,0,0,
1,73,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,False,95565055,95565077,2023,5,20,0,...,,,0,0,0,0,0,0,0,
2,65,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,False,95565055,95565077,2023,5,21,0,...,,,0,0,0,0,0,0,0,
3,49,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,True,95565055,95565077,2023,5,21,0,...,,,0,0,0,0,0,0,0,
4,45,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,True,95565055,95565077,2023,5,22,0,...,,,0,0,0,0,0,0,0,
5,63,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,False,95565055,95565077,2023,5,22,0,...,,,0,0,0,0,0,0,0,
6,30,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,True,95565055,95565077,2023,5,23,0,...,,,0,0,0,0,0,0,0,
7,61,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,False,95565055,95565077,2023,5,23,0,...,,,0,0,0,0,0,0,0,
8,28,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,True,95565055,95565077,2023,5,24,0,...,,,0,0,0,0,0,0,0,
9,69,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,False,95565055,95565077,2023,5,24,0,...,,,0,0,0,0,0,0,0,
10,38,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,True,95565055,95565077,2023,5,25,0,...,,,0,0,0,0,0,0,0,
11,69,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,False,95565055,95565077,2023,5,25,0,...,,,0,0,0,0,0,0,0,
12,32,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,True,95565055,95565077,2023,5,26,0,...,,,0,0,0,0,0,0,0,
13,62,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,False,95565055,95565077,2023,5,26,0,...,,,0,0,0,0,0,0,0,
14,53,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,True,95565055,95565077,2023,5,27,0,...,,,0,0,0,0,0,0,0,
15,60,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,False,95565055,95565077,2023,5,27,0,...,,,0,0,0,0,0,0,0,
16,36,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,True,95565055,95565077,2023,5,28,0,...,,,0,0,0,0,0,0,0,
17,67,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,False,95565055,95565077,2023,5,28,0,...,,,0,0,0,0,0,0,0,
18,32,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,True,95565055,95565077,2023,5,29,0,...,,,0,0,0,0,0,0,0,
19,54,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,False,95565055,95565077,2023,5,29,0,...,,,0,0,0,0,0,0,0,
20,52,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,False,95565055,95565077,2023,5,30,0,...,,,0,0,0,0,0,0,0,
21,22,PRICE_UNIT_WHOLE,PRICE_UPDATE_STATUS_UNSPECIFIED,True,95565055,95565077,2023,5,30,0,...,,,0,0,0,0,0,0,0,